# Generated by Django 5.2.16 on 2026-07-28 06:36

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("VECTOR_DATASET", "Vector dataset"),
                            ("RASTER_DATASET", "Raster dataset"),
                            ("TABLE_DATASET", "Table dataset"),
                            ("MAP", "Map"),
                            ("SCENE", "Scene"),
                            ("DASHBOARD", "Dashboard"),
                            ("STORY", "Story"),
                            ("DOCUMENT", "Document"),
                            ("SERVICE", "Service"),
                            ("APPLICATION", "Application"),
                            ("ANALYSIS_RESULT", "Analysis result"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "Private"),
                            ("ORGANIZATION", "Organization"),
                            ("AUTHENTICATED", "Authenticated"),
                            ("PUBLIC", "Public"),
                        ],
                        db_index=True,
                        default="PRIVATE",
                        max_length=24,
                    ),
                ),
                (
                    "lifecycle_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROCESSING", "Processing"),
                            ("READY", "Ready"),
                            ("PUBLISHED", "Published"),
                            ("FAILED", "Failed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                (
                    "spatial_extent",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        null=True,
                        srid=4326,
                    ),
                ),
                ("temporal_start", models.DateTimeField(blank=True, null=True)),
                ("temporal_end", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "slug"),
                        name="resource_owner_slug_unique",
                    )
                ],
            },
        ),
    ]
