# Generated by Django 5.2.16 on 2026-07-28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=512)),
                (
                    "content_type",
                    models.CharField(default="application/octet-stream", max_length=255),
                ),
                ("declared_size", models.PositiveBigIntegerField()),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("bucket", models.CharField(max_length=255)),
                ("object_key", models.CharField(max_length=1024, unique=True)),
                ("multipart_upload_id", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATING", "Initiating"),
                            ("UPLOADING", "Uploading"),
                            ("COMPLETING", "Completing"),
                            ("ABORTING", "Aborting"),
                            ("COMPLETED", "Completed"),
                            ("ABORTED", "Aborted"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="INITIATING",
                        max_length=16,
                    ),
                ),
                ("part_size", models.PositiveBigIntegerField()),
                ("part_count", models.PositiveIntegerField()),
                ("completed_parts", models.JSONField(blank=True, default=list)),
                ("actual_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("object_etag", models.CharField(blank=True, max_length=255)),
                ("object_version_id", models.CharField(blank=True, max_length=255)),
                ("failure_code", models.CharField(blank=True, max_length=100)),
                ("failure_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("aborted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_sessions",
                        to="resources.resource",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["created_by", "status"],
                        name="upload_owner_status_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(declared_size__gt=0),
                        name="upload_declared_size_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(part_count__gte=1, part_count__lte=10000),
                        name="upload_part_count_range",
                    ),
                ],
            },
        ),
    ]
