# Generated by Django 5.2.16 on 2026-07-29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("datasets", "0004_raster_publication"),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map_document",
                        to="resources.resource",
                    ),
                ),
            ],
            options={"ordering": ("-updated_at",)},
        ),
        migrations.CreateModel(
            name="MapDocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("document", models.JSONField(default=dict)),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("activation_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="map_document_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "map_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="maps.mapdocument",
                    ),
                ),
            ],
            options={
                "ordering": ("map_document", "version_number"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("map_document", "version_number"),
                        name="map_document_version_number_unique",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="mapdocument",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="maps.mapdocumentversion",
            ),
        ),
        migrations.CreateModel(
            name="MapDocumentVersionActivation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial activation"),
                            ("SAVE", "Save and activate"),
                            ("ROLLBACK", "Rollback"),
                            ("MANUAL", "Manual activation"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="map_document_version_activations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activation_departures",
                        to="maps.mapdocumentversion",
                    ),
                ),
                (
                    "map_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_activations",
                        to="maps.mapdocument",
                    ),
                ),
                (
                    "to_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activation_arrivals",
                        to="maps.mapdocumentversion",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="MapLayerReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ordinal", models.PositiveIntegerField()),
                ("client_layer_id", models.CharField(max_length=128)),
                ("title", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[("VECTOR", "Vector"), ("RASTER", "Raster")],
                        max_length=16,
                    ),
                ),
                (
                    "binding_mode",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current dataset version"),
                            ("PINNED", "Pinned dataset version"),
                        ],
                        default="CURRENT",
                        max_length=16,
                    ),
                ),
                ("source_layer_name", models.CharField(blank=True, max_length=255)),
                ("visible", models.BooleanField(default=True)),
                ("opacity", models.FloatField(default=1.0)),
                ("min_zoom", models.FloatField(blank=True, null=True)),
                ("max_zoom", models.FloatField(blank=True, null=True)),
                ("style", models.JSONField(blank=True, default=dict)),
                ("filter", models.JSONField(blank=True, null=True)),
                ("popup", models.JSONField(blank=True, default=dict)),
                ("legend", models.JSONField(blank=True, default=dict)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="map_layer_references",
                        to="datasets.dataset",
                    ),
                ),
                (
                    "dataset_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="map_layer_references",
                        to="datasets.datasetversion",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layer_references",
                        to="maps.mapdocumentversion",
                    ),
                ),
            ],
            options={
                "ordering": ("ordinal",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("version", "ordinal"),
                        name="map_layer_version_ordinal_unique",
                    ),
                    models.UniqueConstraint(
                        fields=("version", "client_layer_id"),
                        name="map_layer_version_client_id_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(opacity__gte=0.0, opacity__lte=1.0),
                        name="map_layer_opacity_range",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(min_zoom__isnull=True)
                            | models.Q(max_zoom__isnull=True)
                            | models.Q(min_zoom__lte=models.F("max_zoom"))
                        ),
                        name="map_layer_zoom_order",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                binding_mode="CURRENT",
                                dataset_version__isnull=True,
                            )
                            | models.Q(
                                binding_mode="PINNED",
                                dataset_version__isnull=False,
                            )
                        ),
                        name="map_layer_binding_version_consistency",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(kind="VECTOR")
                            & ~models.Q(source_layer_name="")
                        )
                        | models.Q(kind="RASTER", source_layer_name=""),
                        name="map_layer_source_name_by_kind",
                    ),
                ],
            },
        ),
    ]
