# Generated by Django 5.2.16 on 2026-07-28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("datasets", "0002_vector_quality_and_tiles"),
        ("jobs", "0002_job_execution_lifecycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("GEOJSON", "GeoJSON"),
                            ("CSV", "CSV"),
                            ("GEOPACKAGE", "GeoPackage"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("selected_fields", models.JSONField(blank=True, default=list)),
                ("bbox", models.JSONField(blank=True, default=list)),
                ("bucket", models.CharField(blank=True, max_length=255)),
                ("object_key", models.CharField(blank=True, max_length=1024)),
                ("object_version_id", models.CharField(blank=True, max_length=255)),
                ("object_etag", models.CharField(blank=True, max_length=255)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("result_filename", models.CharField(blank=True, max_length=255)),
                ("result_size", models.PositiveBigIntegerField(default=0)),
                ("failure_code", models.CharField(blank=True, max_length=100)),
                ("failure_message", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vector_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vector_export",
                        to="jobs.job",
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="datasets.vectorlayer",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["created_by", "status"],
                        name="vec_export_owner_status",
                    ),
                    models.Index(
                        fields=["status", "expires_at"],
                        name="vec_export_status_expiry",
                    ),
                ],
            },
        ),
    ]
