# Generated by Django 5.2.16 on 2026-07-28 06:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourcePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("GROUP", "Organization group"),
                            ("ORGANIZATION", "Organization"),
                            ("AUTHENTICATED", "Authenticated users"),
                            ("ANONYMOUS", "Anonymous users"),
                            ("SHARE_LINK", "Share link"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("subject_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("VIEW", "View"),
                            ("DOWNLOAD", "Download"),
                            ("EDIT", "Edit"),
                            ("PUBLISH", "Publish"),
                            ("MANAGE", "Manage"),
                            ("OWNER", "Owner"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_permissions_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_grants",
                        to="resources.resource",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["resource", "subject_type", "subject_id"],
                        name="res_perm_subject_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource", "subject_type", "subject_id", "action"),
                        name="resource_permission_unique",
                        nulls_distinct=False,
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("subject_id__isnull", True),
                                (
                                    "subject_type__in",
                                    ("AUTHENTICATED", "ANONYMOUS"),
                                ),
                            ),
                            models.Q(
                                ("subject_id__isnull", False),
                                (
                                    "subject_type__in",
                                    ("USER", "GROUP", "ORGANIZATION", "SHARE_LINK"),
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="resource_permission_subject_shape",
                    ),
                ],
            },
        ),
    ]
