SECRET_KEY = "dataset-inspection-integration-only"
INSTALLED_APPS: list[str] = []
DATABASES: dict[str, object] = {}
USE_TZ = True

DATASET_INSPECTION_MAX_ARCHIVE_MEMBERS = 10_000
DATASET_INSPECTION_MAX_UNCOMPRESSED_SIZE = 1024 * 1024 * 1024
DATASET_INSPECTION_MAX_COMPRESSION_RATIO = 100.0
